# Generated by Django 4.0.6 on 2022-07-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_pj', models.CharField(max_length=30)),
                ('duong_dan', models.CharField(max_length=100)),
            ],
        ),
    ]
